const facilities=[
{id:'singapore',name:'المدرسة السنغافورية',color:'#dcecff',accent:'#2f6fb3'},
{id:'rawad-school',name:'مدرسة رواد الأمل',color:'#e7f7ed',accent:'#34895d'},
{id:'iqra',name:'مدرسة اقرأ',color:'#fff3da',accent:'#b7791f'},
{id:'ihsan',name:'مدرسة إحسان',color:'#f2e9ff',accent:'#7b4db2'},
{id:'bureij-center',name:'مركز رواد الأمل للتعليم والتدريب – البريج',color:'#e7f7f7',accent:'#277c80'},
{id:'deir-center',name:'مركز رواد الأمل للتعليم والتدريب – دير البلح',color:'#ffe8ec',accent:'#ad4b61'},
{id:'rawad-kindergarten',name:'روضة رواد الأمل',color:'#fff0e4',accent:'#b66b35'}
];
const seed={
'singapore':[{name:'نموذج طالب',stage:'الصف الأول',section:'أ',phone:'',paid:0,balance:0}],
'rawad-school':[],'iqra':[],'ihsan':[],'bureij-center':[],'deir-center':[],'rawad-kindergarten':[]
};
let data=JSON.parse(localStorage.getItem('lasERPData')||'null')||seed;
let role='admin',currentFacility='singapore',activeTab='students';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('lasERPData',JSON.stringify(data))}
function students(fid){return data[fid]||[]}
function totalPaid(fid){return students(fid).reduce((a,s)=>a+(+s.paid||0),0)}
function totalBalance(fid){return students(fid).reduce((a,s)=>a+(+s.balance||0),0)}
function stages(fid){const map={};students(fid).forEach(s=>{const k=s.stage||'غير محدد';if(!map[k])map[k]={count:0,sections:new Set};map[k].count++;map[k].sections.add(s.section||'-')});return map}
function setupSelectors(){const fs=$('#facilitySelect');fs.innerHTML=facilities.map(f=>`<option value="${f.id}">${f.name}</option>`).join('');fs.value=currentFacility;$('#roleSelect').value=role;fs.onchange=e=>{currentFacility=e.target.value;render()};$('#roleSelect').onchange=e=>{role=e.target.value;render()}}
function renderStats(){const all=facilities.reduce((a,f)=>a+students(f.id).length,0);const p=facilities.reduce((a,f)=>a+totalPaid(f.id),0),b=facilities.reduce((a,f)=>a+totalBalance(f.id),0);$('#adminStats').innerHTML=`<div class="stat">إجمالي المرافق<b>${facilities.length}</b></div><div class="stat">إجمالي الطلبة<b>${all}</b></div><div class="stat">إجمالي المدفوع<b>${p.toLocaleString()}</b></div><div class="stat">إجمالي المتبقي<b>${b.toLocaleString()}</b></div>`}
function renderCards(){const box=$('#facilityCards');box.innerHTML=facilities.map(f=>`<article class="facility-card" style="background:${f.color}"><h3>${f.name}</h3><p>الطلبة: <b>${students(f.id).length}</b></p><p>المراحل: <b>${Object.keys(stages(f.id)).length}</b></p><button onclick="openFacility('${f.id}')">فتح المساحة</button></article>`).join('')}
window.openFacility=id=>{currentFacility=id;$('#facilitySelect').value=id;role=role||'admin';$('#facilityCards').classList.add('hidden');$('#facilityView').classList.remove('hidden');renderFacility()}
function renderFacility(){const f=facilities.find(x=>x.id===currentFacility),st=stages(f.id);$('#viewTitle').textContent=role==='admin'?'إدارة المرفق':'مساحة مدير المرفق';$('#facilityHero').style.background=f.color;$('#facilityHero').innerHTML=`<h2 style="margin:0;color:${f.accent}">${f.name}</h2><p>مساحة بيانات مستقلة — لا تظهر بيانات المرافق الأخرى لمدير هذا المرفق.</p>`;$('#facilityStats').innerHTML=`<div class="stat">الطلبة<b>${students(f.id).length}</b></div><div class="stat">المراحل<b>${Object.keys(st).length}</b></div><div class="stat">المدفوع<b>${totalPaid(f.id).toLocaleString()}</b></div><div class="stat">المتبقي<b>${totalBalance(f.id).toLocaleString()}</b></div>`;renderTab()}
function renderTab(){const fid=currentFacility,c=$('#tabContent');$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));if(activeTab==='students'){const rows=students(fid).map((s,i)=>`<tr><td>${i+1}</td><td>${s.name}</td><td>${s.stage}</td><td>${s.section}</td><td>${s.phone||'-'}</td><td>${(+s.paid||0).toLocaleString()}</td><td>${(+s.balance||0).toLocaleString()}</td></tr>`).join('');c.innerHTML=`<div class="table-wrap"><table><thead><tr><th>#</th><th>اسم الطالب</th><th>المرحلة</th><th>الشعبة</th><th>الهاتف</th><th>المدفوع</th><th>المتبقي</th></tr></thead><tbody>${rows||'<tr><td colspan="7">لا توجد سجلات بعد</td></tr>'}</tbody></table></div>`}else if(activeTab==='stages'){const st=stages(fid);c.innerHTML=`<div class="stage-grid">${Object.entries(st).map(([k,v])=>`<div class="stage-card"><h3>${k}</h3><p>${v.count} طالب/ة</p><p>الشعب: ${[...v.sections].join('، ')}</p></div>`).join('')||'<p>لا توجد مراحل مسجلة بعد.</p>'}</div>`}else if(activeTab==='finance'){c.innerHTML=`<div class="table-wrap"><table><thead><tr><th>المؤشر</th><th>القيمة</th></tr></thead><tbody><tr><td>إجمالي المبالغ المدفوعة</td><td>${totalPaid(fid).toLocaleString()}</td></tr><tr><td>إجمالي المبالغ المتبقية</td><td>${totalBalance(fid).toLocaleString()}</td></tr><tr><td>عدد السجلات المالية</td><td>${students(fid).length}</td></tr></tbody></table></div>`}else{const f=facilities.find(x=>x.id===fid);c.innerHTML=`<div class="backup-box"><h3>Backup مستقل — ${f.name}</h3><p>كل مرفق يمتلك ملف تصدير مستقل. عند ربط Google Sheets لاحقًا يوضع Spreadsheet ID مستقل لكل مرفق في ملف الإعدادات.</p><button onclick="downloadCSV('${fid}')">تنزيل CSV لهذا المرفق</button></div>`}}
$$('.tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;renderTab()});
$('#addStudentBtn').onclick=()=>$('#studentDialog').showModal();$('#studentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const fd=new FormData(e.target),obj=Object.fromEntries(fd.entries());data[currentFacility]=data[currentFacility]||[];data[currentFacility].push(obj);save();e.target.reset();render()});
window.downloadCSV=fid=>{const f=facilities.find(x=>x.id===fid),cols=['name','stage','section','phone','paid','balance'];const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+[['الاسم','المرحلة','الشعبة','الهاتف','المدفوع','المتبقي'].map(esc).join(','),...students(fid).map(r=>cols.map(k=>esc(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${fid}-backup.csv`;a.click();URL.revokeObjectURL(a.href)};$('#backupBtn').onclick=()=>downloadCSV(currentFacility);
function render(){const admin=role==='admin';$('#adminStats').classList.toggle('hidden',!admin);$('#facilitySelect').classList.toggle('hidden',admin);if(admin){$('#facilityCards').classList.remove('hidden');$('#facilityView').classList.add('hidden');$('#viewTitle').textContent='المرافق التعليمية';renderStats();renderCards()}else{$('#facilityCards').classList.add('hidden');$('#facilityView').classList.remove('hidden');renderFacility()}}
setupSelectors();render();